### ISSUE TITLE
Older version of rcon package causes `pip install mciwb` to fail

### ISSUE THREAD

**Issue by seth-dobson** [gilesknap/mciwb#63]
It appears mciwb is not compatible with rcon 2.1.1.  But this is the version of rcon that is installed with python 3.9. I am unable to install the latest version of rcon. Which means, I can't install mciwb. Any help would be greatly appreciated.

```
ERROR: Could not find a version that satisfies the requirement rcon>=2.3.6 (from mcwb>=0.2.1->mciwb) (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.12, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 2.0.0, 2.0.1, 2.0.2, 2.0.8, 2.0.9, 2.1.0, 2.1.1)
ERROR: No matching distribution found for rcon>=2.3.6 (from mcwb>=0.2.1->mciwb)
```

**Comment by gilesknap** [comment]
Unfortunately, in order to pick up some fixes in the latest version of rcon I needed to make this project depend on Python3.10.

If this is a real issue for you then we  could pick up the earlier version of rcon. The bug it fixes is retrieving very long nbt data, and probably the only place this comes up is in asking for a player's data.

If you are unable to switch to Python3.10 then let me know and I'll make some releases that are 3.9 compatible (with the caveat of the bug above).

I also note that setup.cfg currently allows installing mciwb with 3.9 and hence enabling the issue you are seeing.

**Comment by gilesknap** [comment]
Ah. I also note that the released instructions tell you to install Python3.9.

The new branch that I have not yet merged does use python3.10
https://gilesknap.github.io/mciwb/containers/user/tutorials/01-setup.html#python

My apologies, I've neglected this project recently because there has been no interest in it! I'll get the new work merged this weekend.

**Comment by seth-dobson** [comment]
No worries. I look forward to the updates. In the meantime I will try upgrading to 3.10.

**Comment by gilesknap** [comment]
OK - I've got the new branch's CI working and merged it. Future users will be directed to install Python 3.10.

**Comment by gilesknap** [comment]
@seth-dobson can I ask what OS you are using?

I'm developing on linux, doing some testing on Windows.

I'm interested to know how painful the install is for Windows or Mac users.

Thanks.
